name: ancient_arena
description: "A professional 2D fighting game built with Flutter and Flame."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.14.0 # Thư viện game engine cốt lõi [cite: 8]
  flame_audio: ^2.1.0 # Quản lý và phát âm thanh tối ưu hiệu năng [cite: 8]
  flutter_bloc: ^8.1.3 # Quản lý trạng thái ứng dụng [cite: 1]

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
